### ISSUE TITLE
Is there anything I can do for you

### ISSUE THREAD

**Issue by LTreeshu** [area-of-dev/apprepo.AppImage#10]
Hello, buddy, what's wrong with our website? Why can't we download the application now? Is there anything I can do for you

**Comment by AlexWoroschilow** [comment]
Hi there, 

i am currently facing few challenges:

1. github actions are deactivated for all repositories making it impossible to update the apps using this tool
![image](https://user-images.githubusercontent.com/3255923/226211936-45d879ef-29cf-4434-84ac-708ae29e10fc.png)
3. It was done after a migration to the github actions from the selfhosted jenkins instance
4. It was done after a migration to the github releases for the hosting of the AppImages. 
5. I need to finalise the migration to the container-based build of the AppImages for the rest of the app collection.
6. I was contacted regarding the copyright issue. 

There are 2 problems stopping the project from being online:

1. Proprietary applications (jetbrains, microsoft, etc...). 
     > It can be easily solved by just hidding/removing them from the public access
2. Migration to the container-based build and hosting of the packages by github. 
     > The task is straightforward but very time consuming
3. The problem of updating the packages need to be solved. 
   
I see the first 2 problems as critical and stopping the project from being online. The first one can be solved in a few minutes, the second is very time consuming. The last one can be solved later. 

This is how the situation looks like now. Any help is welcome. 
If you are ready to help please think about what you can do and let us discuss the plan.

**Comment by LTreeshu** [comment]
My skills are as follows:

1. I can use appimagetool to package the appimge application from binary.
2. I can do some Chinese translation work.

**Comment by AlexWoroschilow** [comment]
@LTreeshu i will appreciate you help with the screenshots for the applications. Let me know if it is something you are interested in.
