### ISSUE TITLE
Where do I make package request?

### ISSUE THREAD

**Issue by Abhinav1217** [area-of-dev/apprepo.AppImage#5]
Not just package request, I would also like to contribute either by helping maintaining docs, or testing or even building appimages, once I learn properly. Is there a meta repo where I can make package request? 

I am looking to ask for https://lapce.dev/ IDE, it is open source and provide .tar.gz downloads. I would love to get an appimage for that.

**Comment by AlexWoroschilow** [comment]
Hi Abhinav,
happy new year!

I am glad to hear that.

Please create a issue in this repo with the package request, where the
progress will be tracked.
I will provide the info there.

Best,
Alex





Am Mo., 26. Dez. 2022 um 05:56 Uhr schrieb Abhinav Kulshreshtha <
***@***.***>:

**Comment by Abhinav1217** [comment]
Happy New year to you too. 

I have opened a new issue area-of-dev/Lapce.AppImage#1 for the package I was requesting. 

Thanks for taking an Interest.
